# read the text file (renamed as hpc.txt)
hpc <- read.table("hpc.txt", header=TRUE, sep=";")
hpc$Date <- strptime(hpc$Date, '%d/%m/%Y')
hpc$Date <- as.Date(hpc$Date)
shpc <- subset(hpc, hpc$Date >= as.Date("2007-02-01") & hpc$Date <= as.Date("2007-02-02"))

# plot
shpc$Global_active_power <- as.numeric(as.character(shpc$Global_active_power))
shpc$Voltage <- as.numeric(as.character(shpc$Voltage))
shpc$Sub_metering_1 <- as.numeric(as.character(shpc$Sub_metering_1))
shpc$Sub_metering_2 <- as.numeric(as.character(shpc$Sub_metering_2))
shpc$Sub_metering_3 <- as.numeric(as.character(shpc$Sub_metering_3))
shpc$Global_reactive_power <- as.numeric(as.character(shpc$Global_reactive_power))
n <- length(shpc$Date)
m <- length(shpc$Date[weekdays(shpc$Date)=="Thursday"])
datetime <- 1:n
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(datetime, shpc$Global_active_power, type="l", xlab="", ylab="Global Active Power", main=NULL, xaxt='n')
axis(1,at=c(1,m,n),labels=c("Thurs", "Fri", "Sat"),las=2)
plot(datetime, shpc$Voltage, type="l", xlab="", ylab="Voltage", main=NULL, xaxt='n')
axis(1,at=c(1,m,n),labels=c("Thurs", "Fri", "Sat"),las=2)
plot(datetime, shpc$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", main=NULL, xaxt='n')
lines(shpc$Sub_metering_2, type="l", col="red")
lines(shpc$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c(1, 2, "blue"), lty = c(1, 1, 1), cex = 0.8, merge = TRUE)
axis(1,at=c(1,m,n),labels=c("Thurs", "Fri", "Sat"),las=2)
plot(datetime, shpc$Global_reactive_power, type="l", ylab="Global Reactive Power", main=NULL, xaxt='n')
axis(1,at=c(1,m,n),labels=c("Thurs", "Fri", "Sat"),las=2)
dev.off()