## Loading DataSet
#### Loading Data
```{r}
pml.training <- read.csv("DataSet/pml-training.csv")
pml.testing <- read.csv("DataSet/pml-testing.csv")
```
#### Defining Columns for selecting from DataSet
```{r}
MyCols <- c("accel_arm_x","accel_arm_y","accel_belt_x","accel_belt_y","accel_belt_z","accel_dumbbell_x","accel_dumbbell_y","accel_dumbbell_z","accel_forearm_z","gyros_arm_x","gyros_arm_y","gyros_belt_x","gyros_belt_y","gyros_belt_z","magnet_arm_x","magnet_arm_y","magnet_belt_x","magnet_belt_y","magnet_belt_z","magnet_dumbbell_x","magnet_dumbbell_y","magnet_dumbbell_z","pitch_belt","roll_belt","total_accel_belt","total_accel_dumbbell","yaw_belt","yaw_dumbbell","classe")

MyCols2 <- c("accel_arm_x","accel_arm_y","accel_belt_x","accel_belt_y","accel_belt_z","accel_dumbbell_x","accel_dumbbell_y","accel_dumbbell_z","accel_forearm_z","gyros_arm_x","gyros_arm_y","gyros_belt_x","gyros_belt_y","gyros_belt_z","magnet_arm_x","magnet_arm_y","magnet_belt_x","magnet_belt_y","magnet_belt_z","magnet_dumbbell_x","magnet_dumbbell_y","magnet_dumbbell_z","pitch_belt","roll_belt","total_accel_belt","total_accel_dumbbell","yaw_belt","yaw_dumbbell")
```

We are using following columns from DataSet
```{r}
pml.training <- pml.training[,MyCols]
pml.testing <- pml.testing[,MyCols2]
```

## Defining training and cross validation dataset
```{r}
library(caret)
inTrain <- createDataPartition(y=pml.training$classe,p=0.3,list=FALSE)
myTrain <- pml.training[inTrain,]

myCV <- pml.training[-inTrain,]
```

## Training Algorithm
```{r}
ctrl = trainControl(method = "oob", number = 4)
modFit <- train(classe~.,data=myTrain,method="rf",prox=TRUE,trControl = ctrl,allowParallel=TRUE)
```

## Prediction on 20 set Problems
```{r}
predict(modFit,pml.testing)
```

## Acuracy and Sample Error
```{r}
myCvPred <- predict(modFit,myCV)
confusionMatrix(myCvPred, myCV$classe)
```