library(ggplot2)
data(mtcars)
#plot(mtcars)
boxplot(mpg~am, data=mtcars)
ggplot(mtcars, aes(factor(am), mpg)) + geom_boxplot(aes(fill = factor(am)))
#m <- lm(mpg~am, data=mtcars)
#summary(m)
mwo <- lm(mpg~.-am, data=mtcars)
summary(m)
mw <- lm(mpg~., data=mtcars)
summary(m)
library(lmtest)
lrtest(mwo, mw)
step(mw)
summary(mw)
anova(mw)
#qplot(wt, mpg, data = mtcars, colour = am)
ggplot(mtcars, aes(wt, mpg)) + geom_point(aes(colour = factor(am), size = 4))
p <- ggplot(mtcars, aes(wt, mpg, colour = factor(am))) + geom_point() + stat_smooth(method='lm')
p + facet_grid(. ~ am)
p <- ggplot(mtcars, aes(qsec, mpg, colour = factor(am))) + geom_point() + stat_smooth(method='lm')
p + facet_grid(. ~ am)
p <- ggplot(mtcars, aes(x=mpg)) + geom_histogram(bindwidth=6)
p + facet_grid(. ~ am)
p <- ggplot(mtcars, aes(x=mpg)) + geom_density(aes(fill = factor(am)))
p + facet_grid(. ~ am)
#influence(m)