# read the text file (renamed as hpc.txt)
hpc <- read.table("hpc.txt", header=TRUE, sep=";")
hpc$Date <- strptime(hpc$Date, '%d/%m/%Y')
hpc$Date <- as.Date(hpc$Date)
shpc <- subset(hpc, hpc$Date >= as.Date("2007-02-01") & hpc$Date <= as.Date("2007-02-02"))

# plot
shpc$Global_active_power <- as.numeric(as.character(shpc$Global_active_power))
n <- length(shpc$Date)
m <- length(shpc$Date[weekdays(shpc$Date)=="Thursday"])
png(filename = "plot2.png", width = 480, height = 480)
#unique(weekdays(shpc$Date))
plot(1:n, shpc$Global_active_power, type='l', xlab = "", ylab="Global Active Power (kilowatts)", main=NULL, xaxt='n')
axis(1,at=c(1,m,n),labels=c("Thurs", "Fri", "Sat"),las=2)
dev.off()