# read the text file (renamed as hpc.txt)
hpc <- read.table("hpc.txt", header=TRUE, sep=";")
hpc$Date <- strptime(hpc$Date, '%d/%m/%Y')
hpc$Date <- as.Date(hpc$Date)
shpc <- subset(hpc, hpc$Date >= as.Date("2007-02-01") & hpc$Date <= as.Date("2007-02-02"))

# plot
shpc$Sub_metering_1 <- as.numeric(as.character(shpc$Sub_metering_1))
shpc$Sub_metering_2 <- as.numeric(as.character(shpc$Sub_metering_2))
shpc$Sub_metering_3 <- as.numeric(as.character(shpc$Sub_metering_3))
n <- length(shpc$Date)
m <- length(shpc$Date[weekdays(shpc$Date)=="Thursday"])
png(filename = "plot3.png", width = 480, height = 480)
plot(1:n, shpc$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering", main=NULL, xaxt='n')
lines(shpc$Sub_metering_2, col="red")
lines(shpc$Sub_metering_3, col="blue")
axis(1,at=c(1,m,n),labels=c("Thurs", "Fri", "Sat"),las=2)
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c(1, 2, "blue"), lty = c(1, 1, 1), merge = TRUE)
dev.off()