setwd("E:/Academics/Coursera/Data Cleaning/")

acs <- read.csv("getdata-data-ss06hid.csv")
sort(names(acs))
head(acs)
agricultureLogical <- acs$ACR == 3 & acs$AGS == 6
which(agricultureLogical)

library(jpeg)
img <- readJPEG("getdata-jeff.jpg", native = TRUE)
quantile(img, probs = seq(0, 1, 0.1))

dom <- read.csv("getdata-data-GDP.csv")
names(dom)
head(dom)
edu <- read.csv("getdata-data-EDSTATS_Country.csv")
names(edu)
head(edu)
dj <- merge(dom, edu, by = "CountryCode", all = FALSE)
#unique(dj$CountryCode)
nrow(dj)
head(dj[order(dj$Ranking),][c("Ranking", "Long.Name")], 20)
head(dj[order(dj$Ranking, decreasing=TRUE),][c("Ranking", "Long.Name")], 20)
#merge(dom, edu, by = "CountryCode", all = TRUE)
mean(subset(dj, Income.Group == "High income: OECD")$Ranking)
mean(subset(dj, Income.Group == "High income: nonOECD")$Ranking)
dj$Ranking <- cut(dj$Ranking, quantile(dj$Ranking, seq(0, 1, 0.2)), include.lowest = TRUE)
table(dj$Ranking)
nrow(dj[dj$Ranking == levels(dj$Ranking)[[1]] & dj$Income.Group == "Lower middle income",])